language: node_js
sudo: required
node_js:
- 6.10.3
cache:
  directories:
  - node_modules
before_script:
- git clone --branch master https://github.com/yuwuxing/yuwuxing.github.io.git public
script:
- npm run build
after_success:
- cd public
- git config user.name "zhaoyu"
- git config user.email "yuwuxing@gmail.com"
- git add --all .
- git commit -m "travis ci auto build"
- git push git@github.com:yuwuxing/yuwuxing.github.io.git master
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_9c6e9aaf2fdc_key -iv $encrypted_9c6e9aaf2fdc_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
